#!/bin/bash

set -eux

export GATEWAY_IP=$(os-apply-config --key default-gateway --type netaddress)

if [ -n "$GATEWAY_IP" ]; then

    route add default gw $GATEWAY_IP

    sed -i "/^GATEWAY/d" /etc/sysconfig/network
    echo "GATEWAY=$GATEWAY_IP" >> /etc/sysconfig/network

fi
